### ISSUE TITLE
The camera does not open

### ISSUE THREAD

**Issue by SarthakTandon9** [jitsm555/Flutter-OCR-Scanner#1]
Whenever I try to open the camera in my phone this pops up and the app just closes: 
https://user-images.githubusercontent.com/32408652/84566269-80231c00-ad8d-11ea-9564-2df57f335d5c.jpeg)
This is my log: 
I/le.audoptik_ap( 1039): The ClassLoaderContext is a special shared library.
I/le.audoptik_ap( 1039): The ClassLoaderContext is a special shared library.
I/le.audoptik_ap( 1039): The ClassLoaderContext is a special shared library.
W/le.audoptik_ap( 1039): Accessing hidden field Ljava/nio/Buffer;->address:J (light greylist, reflection)
V/NativeCrypto( 1039): Registering com/google/android/gms/org/conscrypt/NativeCrypto's 286 native methods...
W/le.audoptik_ap( 1039): Accessing hidden method Ljava/security/spec/ECParameterSpec;->getCurveName()Ljava/lang/String; (light greylist, reflection)
D/NetworkSecurityConfig( 1039): No Network Security Config specified, using platform default
I/ProviderInstaller( 1039): Installed default security provider GmsCore_OpenSSL
W/le.audoptik_ap( 1039): Accessing hidden field Ljava/net/Socket;->impl:Ljava/net/SocketImpl; (light greylist, reflection)
W/le.audoptik_ap( 1039): Accessing hidden method Ldalvik/system/CloseGuard;->get()Ldalvik/system/CloseGuard; (light greylist, linking)
W/le.audoptik_ap( 1039): Accessing hidden method Ldalvik/system/CloseGuard;->open(Ljava/lang/String;)V (light greylist, linking)W/le.audoptik_ap( 1039): Accessing hidden field Ljava/io/FileDescriptor;->descriptor:I (light greylist, JNI)
W/le.audoptik_ap( 1039): Accessing hidden method Ljava/security/spec/ECParameterSpec;->setCurveName(Ljava/lang/String;)V (light 
greylist, reflection)
W/le.audoptik_ap( 1039): Accessing hidden method Ldalvik/system/BlockGuard;->getThreadPolicy()Ldalvik/system/BlockGuard$Policy; 
(light greylist, linking)
W/le.audoptik_ap( 1039): Accessing hidden method Ldalvik/system/BlockGuard$Policy;->onNetwork()V (light greylist, linking)
I/flutter ( 1039): NoSuchMethodError: The method '[]' was called on null.
I/flutter ( 1039): Receiver: null
I/flutter ( 1039): Tried calling: []("fullName")
I/flutter ( 1039): NoSuchMethodError: The method '[]' was called on null.
I/flutter ( 1039): Receiver: null
I/flutter ( 1039): Tried calling: []("fullName")
I/le.audoptik_ap( 1039): ProcessProfilingInfo new_methods=5451 is saved saved_to_disk=1 resolve_classes_delay=8000
I/Timeline( 1039): Timeline: Activity_launch_request time:219790754 intent:Intent { cmp=com.example.audoptik_app/io.github.edufolly.fluttermobilevision.ocr.OcrCaptureActivity (has extras) }
E/MethodChannel#flutter_mobile_vision( 1039): Failed to handle method call
E/MethodChannel#flutter_mobile_vision( 1039): android.content.ActivityNotFoundException: Unable to find explicit activity class 
{com.example.audoptik_app/io.github.edufolly.fluttermobilevision.ocr.OcrCaptureActivity}; have you declared this activity in your AndroidManifest.xml?
E/MethodChannel#flutter_mobile_vision( 1039):   at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2020)
E/MethodChannel#flutter_mobile_vision( 1039):   at android.app.Instrumentation.execStartActivity(Instrumentation.java:1679)     
E/MethodChannel#flutter_mobile_vision( 1039):   at android.app.Activity.startActivityForResult(Activity.java:4651)
E/MethodChannel#flutter_mobile_vision( 1039):   at android.app.Activity.startActivityForResult(Activity.java:4609)
E/MethodChannel#flutter_mobile_vision( 1039):   at io.github.edufolly.fluttermobilevision.FlutterMobileVisionDelegate.launchIntent(FlutterMobileVisionDelegate.java:232)
E/MethodChannel#flutter_mobile_vision( 1039):   at io.github.edufolly.fluttermobilevision.FlutterMobileVisionDelegate.read(FlutterMobileVisionDelegate.java:122)
E/MethodChannel#flutter_mobile_vision( 1039):   at io.github.edufolly.fluttermobilevision.FlutterMobileVisionPlugin.onMethodCall(FlutterMobileVisionPlugin.java:174)
E/MethodChannel#flutter_mobile_vision( 1039):   at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:226)
E/MethodChannel#flutter_mobile_vision( 1039):   at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/MethodChannel#flutter_mobile_vision( 1039):   at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:631)
E/MethodChannel#flutter_mobile_vision( 1039):   at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#flutter_mobile_vision( 1039):   at android.os.MessageQueue.next(MessageQueue.java:326)
E/MethodChannel#flutter_mobile_vision( 1039):   at android.os.Looper.loop(Looper.java:165)
E/MethodChannel#flutter_mobile_vision( 1039):   at android.app.ActivityThread.main(ActivityThread.java:6810)
E/MethodChannel#flutter_mobile_vision( 1039):   at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#flutter_mobile_vision( 1039):   at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
E/MethodChannel#flutter_mobile_vision( 1039):   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
D/AndroidRuntime( 1039): Shutting down VM
E/AndroidRuntime( 1039): FATAL EXCEPTION: main
E/AndroidRuntime( 1039): Process: com.example.audoptik_app, PID: 1039
E/AndroidRuntime( 1039): java.lang.IllegalStateException: Reply already submitted
E/AndroidRuntime( 1039):        at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:139)
E/AndroidRuntime( 1039):        at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.error(MethodChannel.java:236)
E/AndroidRuntime( 1039):        at io.github.edufolly.fluttermobilevision.FlutterMobileVisionPlugin$MethodResultWrapper$2.run(FlutterMobileVisionPlugin.java:136)
E/AndroidRuntime( 1039):        at android.os.Handler.handleCallback(Handler.java:873)
E/AndroidRuntime( 1039):        at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime( 1039):        at android.os.Looper.loop(Looper.java:201)
E/AndroidRuntime( 1039):        at android.app.ActivityThread.main(ActivityThread.java:6810)
E/AndroidRuntime( 1039):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 1039):        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
E/AndroidRuntime( 1039):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
I/Process ( 1039): Sending signal. PID: 1039 SIG: 9
Lost connection to device.

Please help me guys!

**Comment by SarthakTandon9** [comment]
Nevermind, i got it, you have to add the dependencies in the android.xml in the android/app/main

**Comment by jitsm555** [comment]
@SarthakTandon9 : Can you raised PR against it?

**Comment by SarthakTandon9** [comment]
@jitsm555 what does raise PR against it mean?? Also just asking do you also have a tutorial on face detection and emotion detection?
Thanks,
Sarthak
